name: Build
on: push
env:
    semantic_version: '19.0.5'
jobs:
    ci:
        name: Application Build
        runs-on: ubuntu-latest
        if: github.actor != 'dependabot[bot]'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  submodules: 'true'

#            - name: Application Build and Test
#              run: |
#                  sudo apt-get install -y uuid-dev uuid-runtime
#                  make
#                  ls -lah

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Getting next release version
              id: semantic
              uses: cycjimmy/semantic-release-action@v3
              with:
                  dry_run: true
                  semantic_version: ${{ env.semantic_version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build AMD64 binary
              uses: docker/build-push-action@v3
              with:
                file: .github/workflows/Dockerfile
                tags: result:amd64
                platforms: linux/amd64
                load: true
                push: false

            - name: Build ARM v7 binary
              uses: docker/build-push-action@v3
              with:
                file: .github/workflows/Dockerfile
                tags: result:arm-v7
                platforms: linux/arm/v7
                load: true
                push: false

            - name: Extract results
              run: |
                for arch in amd64 arm-v7; do
                    id=$(docker create result:$arch)
                    docker cp $id:/build/samler samler.$arch
                    docker rm -v $id
                    file samler.$arch
                done

            - uses: ncipollo/release-action@v1
              if: github.ref == 'refs/heads/master' && steps.semantic.outputs.new_release_version != null
              with:
                artifacts: "release.tar.gz,foo/*.txt"
                bodyFile: "body.md"

            - name: Create Release
              if: github.ref == 'refs/heads/master' && steps.semantic.outputs.new_release_version != null
              uses: cycjimmy/semantic-release-action@v3
              with:
                  semantic_version: ${{ env.semantic_version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Release
              uses: softprops/action-gh-release@v1
              if: github.ref == 'refs/heads/master' && steps.semantic.outputs.new_release_version != null
              with:
                tag_name: ${{ steps.semantic.outputs.new_release_version }}
                files: |
                  samler.amd64
                  samler.arm-v7
